;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                              ;;
;; Copyright (C) KolibriOS team 2013-2024. All rights reserved. ;;
;; Distributed under terms of the GNU General Public License    ;;
;;                                                              ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Éste archivo debe ser editado con codificación CP866

version  cp850    'maxregnerOS versión 1.0.0      ',13,10,13,10,0 ; maxregnerOS - Modern, Vibrant, Powerful
diff16 "fin del código del kernel",0,$
